[16/01/2023 09:47:41] [INFO    ] discord.client: logging in using static token
[16/01/2023 09:48:30] [INFO    ] discord.client: logging in using static token
[16/01/2023 09:48:36] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: dbab660f59d86a5c4380299c8e014811).
[16/01/2023 10:06:38] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:06:45] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: cc91579a1d7c4a1bbc4707751d887ab7).
[16/01/2023 10:09:24] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:09:31] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: b4348cf07f2cf357a8dab8c7f9199edf).
[16/01/2023 10:11:33] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:11:40] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c08c2f848b5157df3942608054f70255).
[16/01/2023 10:12:04] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:12:11] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6f4ea1664eeaa49720fc6b00c598df42).
[16/01/2023 10:12:32] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064143612998320199 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:12:33] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064142845784641546 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:12:34] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064142109436825621 responded with 429. Retrying in 0.39 seconds.
[16/01/2023 10:12:35] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064141611560345660 responded with 429. Retrying in 0.35 seconds.
[16/01/2023 10:12:37] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064140953314668606 responded with 429. Retrying in 0.31 seconds.
[16/01/2023 10:12:38] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064140201263386724 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:12:40] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064139682025324564 responded with 429. Retrying in 0.39 seconds.
[16/01/2023 10:12:41] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064139349115015218 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:12:42] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064138122461454360 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:12:43] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064108211109646356 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:12:45] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064083166844956672 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:12:46] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064082704674586715 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:12:47] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064082425233297428 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:12:48] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064082221956341821 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:12:49] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064081822104948776 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:12:50] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064080524978700308 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:12:51] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064079383377215488 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:12:52] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064076347628064788 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:12:53] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064061515059167295 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:13:49] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:13:55] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 8e7299e1b2c8e63a5c18d378abd03672).
[16/01/2023 10:14:19] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064040426727813140 responded with 429. Retrying in 0.46 seconds.
[16/01/2023 10:14:20] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064040095176458264 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:14:21] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064038412035817582 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:14:22] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064038215134228561 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:14:23] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064038047546622148 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:14:24] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064037845414723654 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:14:26] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1064036874982797414 responded with 429. Retrying in 0.50 seconds.
[16/01/2023 10:16:00] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:16:07] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: efd9478fceafdab0d6eb9b3c072b2b54).
[16/01/2023 10:16:31] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:16:37] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 859cd28767d206da635ecbf43720c98f).
[16/01/2023 10:17:08] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/935402756129304627/messages/1063424677122429008 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:18:04] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:18:11] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 27a3840d35533c06afb6807161d165dd).
[16/01/2023 10:19:11] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:19:18] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 5d3f69958e1a816d47cdcfbeab2e0899).
[16/01/2023 10:21:10] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:21:17] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 9f789469893f6bd0a25bc96bdf52dc01).
[16/01/2023 10:22:59] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:23:05] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ae88a0d981f5ddb1298393a111df3cb7).
[16/01/2023 10:24:11] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:24:18] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 2a342e8c1b0548a7258371c5d2299a11).
[16/01/2023 10:25:09] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:25:16] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 79ec95e219faaf71ba2958f1bca15bdb).
[16/01/2023 10:26:38] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:26:44] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: f014a7e727e936afceffb8eed857dcda).
[16/01/2023 10:27:33] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:27:39] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: eed29170b4a11a65a107d2139233e41e).
[16/01/2023 10:27:53] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'text'
Traceback (most recent call last):
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\commands.py", line 861, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "C:\Users\avart\OneDrive\Máy tính\remind_bot\RemindBot\cogs\server\delete.py", line 43, in _text
    print("=>>", user.id, user.discriminator)
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'text' raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
[16/01/2023 10:28:55] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:29:02] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 26d5289e71c382a5c5c9907c7a5f8c75).
[16/01/2023 10:30:30] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:30:36] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 7e846e36d89b851e88d17a7a086e7918).
[16/01/2023 10:31:19] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:31:26] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e6af85535618ad1adb15f7e73fe375a0).
[16/01/2023 10:31:57] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:32:04] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a6c97d07d8eda7a1937dd2d9305866cb).
[16/01/2023 10:32:45] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948085339321430046 responded with 429. Retrying in 0.42 seconds.
[16/01/2023 10:32:46] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948085247818473563 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:32:47] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948084421645451305 responded with 429. Retrying in 0.33 seconds.
[16/01/2023 10:32:48] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948084280532303933 responded with 429. Retrying in 0.36 seconds.
[16/01/2023 10:32:49] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948084182322655282 responded with 429. Retrying in 0.33 seconds.
[16/01/2023 10:32:50] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948083959613493278 responded with 429. Retrying in 0.34 seconds.
[16/01/2023 10:32:51] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948083834967162951 responded with 429. Retrying in 0.32 seconds.
[16/01/2023 10:32:52] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948083567613853737 responded with 429. Retrying in 0.34 seconds.
[16/01/2023 10:32:53] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948083010899693629 responded with 429. Retrying in 0.31 seconds.
[16/01/2023 10:32:54] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948082920856383520 responded with 429. Retrying in 0.36 seconds.
[16/01/2023 10:32:55] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948082553003311124 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:32:56] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948082431200751666 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:33:29] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:33:36] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: f43610c1b1c22e90bab328d5756844c9).
[16/01/2023 10:34:03] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/967623378301251635 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:34:04] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/967623377978277978 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:34:05] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/967623352447545374 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:34:06] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/967623351793229924 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:34:07] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/967623326459654204 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:34:08] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/967623326094753854 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:34:09] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/967621947246665758 responded with 429. Retrying in 0.54 seconds.
[16/01/2023 10:34:11] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/967621940422508575 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:34:12] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/967621939923390535 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:34:13] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/967621923708211221 responded with 429. Retrying in 0.60 seconds.
[16/01/2023 10:34:15] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'text'
Traceback (most recent call last):
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\commands.py", line 861, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "C:\Users\avart\OneDrive\Máy tính\remind_bot\RemindBot\cogs\server\delete.py", line 58, in _text
    await interaction.followup.send(f"Đã xóa **{count}** tin nhắn", ephemeral = True)
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\webhook\async_.py", line 1726, in send
    data = await adapter.execute_webhook(
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\webhook\async_.py", line 218, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'text' raised an exception: NotFound: 404 Not Found (error code: 10008): Unknown Message
[16/01/2023 10:36:27] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:36:34] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 4a64debf708cdee8709a7bac69002729).
[16/01/2023 10:37:59] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:38:06] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6086816f26f96c360d5bf25da941cee1).
[16/01/2023 10:38:36] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/967621796616618054 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:38:38] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/959002178738077716 responded with 429. Retrying in 0.37 seconds.
[16/01/2023 10:38:39] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948087230939951134 responded with 429. Retrying in 0.35 seconds.
[16/01/2023 10:38:40] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948087229362897006 responded with 429. Retrying in 0.34 seconds.
[16/01/2023 10:38:41] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948085255158517821 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:38:43] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948083571707490375 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:38:45] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948082922932535377 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:38:46] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948082190225408072 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:38:48] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948081715363070043 responded with 429. Retrying in 0.43 seconds.
[16/01/2023 10:38:49] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'text'
Traceback (most recent call last):
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\commands.py", line 861, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "C:\Users\avart\OneDrive\Máy tính\remind_bot\RemindBot\cogs\server\delete.py", line 59, in _text
    message = await interaction.followup.send(f"Đã xóa **{count}** tin nhắn", ephemeral = True)
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\webhook\async_.py", line 1726, in send
    data = await adapter.execute_webhook(
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\webhook\async_.py", line 218, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'text' raised an exception: NotFound: 404 Not Found (error code: 10008): Unknown Message
[16/01/2023 10:42:26] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:42:33] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 7a2446d0289ad4c465af49e3547a1f9d).
[16/01/2023 10:49:05] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948065775762173982 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:49:07] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948065605456642078 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:49:09] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948065207870193745 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:49:10] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948065203172548668 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:49:12] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948064705111543859 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:49:14] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/948063867722956830 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 10:49:15] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'text'
Traceback (most recent call last):
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\commands.py", line 861, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "C:\Users\avart\OneDrive\Máy tính\remind_bot\RemindBot\cogs\server\delete.py", line 61, in _text
    message = await interaction.followup.send(f"Đã xóa **{count}** tin nhắn", ephemeral = True)
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\webhook\async_.py", line 1726, in send
    data = await adapter.execute_webhook(
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\webhook\async_.py", line 218, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\avart\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'text' raised an exception: NotFound: 404 Not Found (error code: 10008): Unknown Message
[16/01/2023 10:49:28] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:49:36] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e43faf0fa7736d586e4cf3f06689bc8a).
[16/01/2023 10:52:29] [INFO    ] discord.client: logging in using static token
[16/01/2023 10:52:35] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 350b37e5c4a5587dbd761ca08eacdb1c).
[16/01/2023 10:52:57] [WARNING ] discord.http: We are being rate limited. DELETE https://discord.com/api/v10/channels/929978924107190292/messages/933574369337290802 responded with 429. Retrying in 0.30 seconds.
[16/01/2023 11:48:35] [INFO    ] discord.client: logging in using static token
[16/01/2023 11:48:59] [INFO    ] discord.client: logging in using static token
[16/01/2023 11:49:35] [INFO    ] discord.client: logging in using static token
[16/01/2023 11:49:41] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a8fc1bfcd03ff029ea342dac97732e34).
[16/01/2023 11:54:31] [INFO    ] discord.client: logging in using static token
[16/01/2023 11:54:38] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 137ea1b40cea72a56a37ffabe97d84a2).
[14/03/2023 08:27:43] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[14/03/2023 08:27:43] [INFO    ] discord.client: logging in using static token
[14/03/2023 08:28:33] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[14/03/2023 08:28:33] [INFO    ] discord.client: logging in using static token
[14/03/2023 08:28:45] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[14/03/2023 08:28:45] [INFO    ] discord.client: logging in using static token
[14/03/2023 08:28:49] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: dee44871ef23ac0542ffd1ad34caa148).
[14/03/2023 08:43:00] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'create'
Traceback (most recent call last):
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\commands.py", line 841, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tungnd\Desktop\discord_bot\cogs\server\channel.py", line 63, in _create
    find = await self.check_user(member.id, guild.id, "guildID")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tungnd\Desktop\discord_bot\cogs\server\channel.py", line 25, in check_user
    find = await self.db.find({"onwerID" : memberID, name : channelID})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object NoneType can't be used in 'await' expression

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\commands.py", line 856, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'create' raised an exception: TypeError: object NoneType can't be used in 'await' expression
[14/03/2023 08:44:12] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[14/03/2023 08:44:12] [INFO    ] discord.client: logging in using static token
[14/03/2023 08:44:16] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 91267a30acceddac03c14ea5c44422b5).
[14/03/2023 08:44:32] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'create'
Traceback (most recent call last):
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\commands.py", line 841, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tungnd\Desktop\discord_bot\cogs\server\channel.py", line 63, in _create
    find = await self.check_user(member.id, guild.id, "guildID")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tungnd\Desktop\discord_bot\cogs\server\channel.py", line 25, in check_user
    find = await self.db.find({"onwerID" : memberID, name : channelID})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object NoneType can't be used in 'await' expression

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\commands.py", line 856, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'create' raised an exception: TypeError: object NoneType can't be used in 'await' expression
[14/03/2023 08:45:07] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[14/03/2023 08:45:07] [INFO    ] discord.client: logging in using static token
[14/03/2023 08:45:12] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 587c0524cd9c1bbd41c9dfb3dcfa7082).
[14/03/2023 08:45:46] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'create'
Traceback (most recent call last):
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\commands.py", line 841, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tungnd\Desktop\discord_bot\cogs\server\channel.py", line 74, in _create
    await self.addChannel(member.id, channel.id, guild.id, float_seconds)
  File "C:\Users\tungnd\Desktop\discord_bot\cogs\server\channel.py", line 22, in addChannel
    await self.db.insert(data)
TypeError: object NoneType can't be used in 'await' expression

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\commands.py", line 856, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'create' raised an exception: TypeError: object NoneType can't be used in 'await' expression
[14/03/2023 08:49:24] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[14/03/2023 08:49:24] [INFO    ] discord.client: logging in using static token
[14/03/2023 08:49:28] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: dbac3725a5681babc3d8d56673cfa8ec).
[14/03/2023 08:51:41] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'delete'
Traceback (most recent call last):
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\commands.py", line 841, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tungnd\Desktop\discord_bot\cogs\server\channel.py", line 97, in _delete
    await self.db.remove(data)
TypeError: object NoneType can't be used in 'await' expression

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tungnd\Desktop\discord_bot\env\Lib\site-packages\discord\app_commands\commands.py", line 856, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'delete' raised an exception: TypeError: object NoneType can't be used in 'await' expression
[14/03/2023 08:52:04] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[14/03/2023 08:52:04] [INFO    ] discord.client: logging in using static token
[14/03/2023 08:52:08] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: be77085701875a4008fc312c998c065f).
[14/03/2023 08:53:54] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[14/03/2023 08:53:54] [INFO    ] discord.client: logging in using static token
[14/03/2023 08:53:58] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 2471b12dbeae64e7be03a4386b35c68a).
[14/03/2023 08:56:20] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[14/03/2023 08:56:20] [INFO    ] discord.client: logging in using static token
[14/03/2023 08:56:23] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a1f9c2805839821ad9916bf6c6bbebcc).
